// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/konsen.proto

package konsen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV) Reset() {
	*x = KV{}
	mi := &file_proto_konsen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_proto_konsen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_proto_konsen_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KvList        []*KV                  `protobuf:"bytes,1,rep,name=kv_list,json=kvList,proto3" json:"kv_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVList) Reset() {
	*x = KVList{}
	mi := &file_proto_konsen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVList) ProtoMessage() {}

func (x *KVList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_konsen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVList.ProtoReflect.Descriptor instead.
func (*KVList) Descriptor() ([]byte, []int) {
	return file_proto_konsen_proto_rawDescGZIP(), []int{1}
}

func (x *KVList) GetKvList() []*KV {
	if x != nil {
		return x.KvList
	}
	return nil
}

var File_proto_konsen_proto protoreflect.FileDescriptor

const file_proto_konsen_proto_rawDesc = "" +
	"\n" +
	"\x12proto/konsen.proto\x12\x06konsen\",\n" +
	"\x02KV\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"-\n" +
	"\x06KVList\x12#\n" +
	"\akv_list\x18\x01 \x03(\v2\n" +
	".konsen.KVR\x06kvListB\vZ\t./;konsenb\x06proto3"

var (
	file_proto_konsen_proto_rawDescOnce sync.Once
	file_proto_konsen_proto_rawDescData []byte
)

func file_proto_konsen_proto_rawDescGZIP() []byte {
	file_proto_konsen_proto_rawDescOnce.Do(func() {
		file_proto_konsen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_konsen_proto_rawDesc), len(file_proto_konsen_proto_rawDesc)))
	})
	return file_proto_konsen_proto_rawDescData
}

var file_proto_konsen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_konsen_proto_goTypes = []any{
	(*KV)(nil),     // 0: konsen.KV
	(*KVList)(nil), // 1: konsen.KVList
}
var file_proto_konsen_proto_depIdxs = []int32{
	0, // 0: konsen.KVList.kv_list:type_name -> konsen.KV
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_konsen_proto_init() }
func file_proto_konsen_proto_init() {
	if File_proto_konsen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_konsen_proto_rawDesc), len(file_proto_konsen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_konsen_proto_goTypes,
		DependencyIndexes: file_proto_konsen_proto_depIdxs,
		MessageInfos:      file_proto_konsen_proto_msgTypes,
	}.Build()
	File_proto_konsen_proto = out.File
	file_proto_konsen_proto_goTypes = nil
	file_proto_konsen_proto_depIdxs = nil
}
