// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: proto/kv.proto

package konsen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Raw data/command to be stored and applied to the state machine.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReq) Reset() {
	*x = PutReq{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReq) ProtoMessage() {}

func (x *PutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReq.ProtoReflect.Descriptor instead.
func (*PutReq) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *PutReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResp) Reset() {
	*x = PutResp{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResp) ProtoMessage() {}

func (x *PutResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResp.ProtoReflect.Descriptor instead.
func (*PutResp) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *PutResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x06konsen\"\x1c\n" +
	"\x06PutReq\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"H\n" +
	"\aPutResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x1a\n" +
	"\x06GetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"^\n" +
	"\aGetResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2_\n" +
	"\tKVService\x12(\n" +
	"\x03Put\x12\x0e.konsen.PutReq\x1a\x0f.konsen.PutResp\"\x00\x12(\n" +
	"\x03Get\x12\x0e.konsen.GetReq\x1a\x0f.konsen.GetResp\"\x00B\vZ\t./;konsenb\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_kv_proto_goTypes = []any{
	(*PutReq)(nil),  // 0: konsen.PutReq
	(*PutResp)(nil), // 1: konsen.PutResp
	(*GetReq)(nil),  // 2: konsen.GetReq
	(*GetResp)(nil), // 3: konsen.GetResp
}
var file_proto_kv_proto_depIdxs = []int32{
	0, // 0: konsen.KVService.Put:input_type -> konsen.PutReq
	2, // 1: konsen.KVService.Get:input_type -> konsen.GetReq
	1, // 2: konsen.KVService.Put:output_type -> konsen.PutResp
	3, // 3: konsen.KVService.Get:output_type -> konsen.GetResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
